config/routes.rb
StampsDemo::Application.routes.draw do
  resources :shipping_labels
  resources :shipping_rates
  resources :addresses
  match '/getrates', :to => 'shipping_labels#add_on_lookup', :via => :post
  # Root is set to the New action to bypass a extra click durring development.
  root :to => 'shipping_labels#new'

end

app/models/shipping_rate.rb
# currently not intagrated with teh making of a label, but this will get rates for a shippment with valid data.
# TODO: Parse return data to display rates.
class ShippingRate < ActiveRecord::Base
  attr_accessible :from_zip_code, :package_type, :service_type, :ship_date, :to_zip_code, :weight, :rates

  before_create :get_rates

  def get_rates
    rates = Stamps.get_rates(
      :from_zip_code => self.from_zip_code,
      :to_zip_code   => self.to_zip_code,
      :weight_lb     => self.weight,
      :ship_date     => self.ship_date,
      :service_type  => self.service_type,
      :package_type  => self.package_type
    )

    self.rates = rates
  end
end

app/controllers/shipping_rates_controller.rb
class ShippingRatesController < ApplicationController
  # GET /shipping_rates
  # GET /shipping_rates.json
  def index
    @shipping_rates = ShippingRate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shipping_rates }
    end
  end

  # GET /shipping_rates/1
  # GET /shipping_rates/1.json
  def show
    @shipping_rate = ShippingRate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shipping_rate }
    end
  end

  # GET /shipping_rates/new
  # GET /shipping_rates/new.json
  def new
    @shipping_rate = ShippingRate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shipping_rate }
    end
  end

  # GET /shipping_rates/1/edit
  def edit
    @shipping_rate = ShippingRate.find(params[:id])
  end

  # POST /shipping_rates
  # POST /shipping_rates.json
  def create
    @shipping_rate = ShippingRate.new(params[:shipping_rate])

    respond_to do |format|
      if @shipping_rate.save
        format.html { redirect_to @shipping_rate, notice: 'Shipping rate was successfully created.' }
        format.json { render json: @shipping_rate, status: :created, location: @shipping_rate }
      else
        format.html { render action: "new" }
        format.json { render json: @shipping_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shipping_rates/1
  # PUT /shipping_rates/1.json
  def update
    @shipping_rate = ShippingRate.find(params[:id])

    respond_to do |format|
      if @shipping_rate.update_attributes(params[:shipping_rate])
        format.html { redirect_to @shipping_rate, notice: 'Shipping rate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shipping_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipping_rates/1
  # DELETE /shipping_rates/1.json
  def destroy
    @shipping_rate = ShippingRate.find(params[:id])
    @shipping_rate.destroy

    respond_to do |format|
      format.html { redirect_to shipping_rates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shipping_rates_helper.rb
module ShippingRatesHelper
end

app/views/shipping_rates/_form.html.erb
<%= form_for(@shipping_rate) do |f| %>
  <% if @shipping_rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipping_rate.errors.count, "error") %> prohibited this shipping_rate from being saved:</h2>

      <ul>
      <% @shipping_rate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_zip_code %><br />
    <%= f.text_field :from_zip_code %>
  </div>
  <div class="field">
    <%= f.label :to_zip_code %><br />
    <%= f.text_field :to_zip_code %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :ship_date %><br />
    <%= f.date_select :ship_date, :start_year => Date.today.year %>
  </div>
  <div class="field">
    <%= f.label :service_type %><br />
    <%= f.select :service_type, Stamps::Types::SERVICE.map { |s| [ s[1], s[0] ] } %>
  </div>
  <div class="field">
    <%= f.label :package_type %><br />
    <%= f.select :package_type, Stamps::Types::PACKAGE %>
  </div>
  <div class="actions">
    <%= f.submit 'Get Rates' %>
  </div>
<% end %>

app/views/shipping_rates/edit.html.erb
<h1>Editing shipping_rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @shipping_rate %> |
<%= link_to 'Back', shipping_rates_path %>

app/views/shipping_rates/index.html.erb
<h1>Listing shipping_rates</h1>

<table>
  <tr>
    <th>From zip code</th>
    <th>To zip code</th>
    <th>Weight</th>
    <th>Ship date</th>
    <th>Service type</th>
    <th>Package type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shipping_rates.each do |shipping_rate| %>
  <tr>
    <td><%= shipping_rate.from_zip_code %></td>
    <td><%= shipping_rate.to_zip_code %></td>
    <td><%= shipping_rate.weight %></td>
    <td><%= shipping_rate.ship_date %></td>
    <td><%= shipping_rate.service_type %></td>
    <td><%= shipping_rate.package_type %></td>
    <td><%= link_to 'Show', shipping_rate %></td>
    <td><%= link_to 'Edit', edit_shipping_rate_path(shipping_rate) %></td>
    <td><%= link_to 'Destroy', shipping_rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shipping rate', new_shipping_rate_path %>

app/views/shipping_rates/new.html.erb
<h1>New shipping_rate</h1>

<%= render 'form' %>

<%= link_to 'Back', shipping_rates_path %>

app/views/shipping_rates/show.html.erb
<p id="notice"><%= notice %></p>




<h3>Rates</h3>
<div>
  <% @shipping_rate.get_rates.each do |rate| %>
    <div>
      <p>
        Cost: <%= rate[:amount] %>
      </p>
      <p>
        Service Type Code: <%= rate[:service_type] %>
      </p>
      <p>
        Package Type: <%= rate[:package_type] %>
      </p>
      <p>
        Delivery Time: <%= rate[:deliver_days] %>
      </p>
      <p>
        <ul>
        <% rate[:add_ons][:add_on_v4].each do |add_on| %>
          <li>
            Add on Type: <%= add_on[:add_on_type] %>
            <% if add_on[:requires_all_of] %>
              <ul>
                <% if add_on[:requires_all_of][:requires_one_of][:add_on_type_v4].length < 1 %>
                <% add_on[:requires_all_of][:requires_one_of][:add_on_type_v4].each do |type| %>
                  <li>Required add ons: <%= type %></li>
                <% end %>
                <% else %>
                  Required add ons: <%= add_on[:requires_all_of][:requires_one_of][:add_on_type_v4] %>
                <% end %>
              </ul>
            <% end %>
          </li>
        <% end %>
        </ul>
      </p>
      <p>
        <%=  %>
      </p>
      <br>
    </div>
  <% end %>
</div>

<p>
  <b>From zip code:</b>
  <%= @shipping_rate.from_zip_code %>
</p>

<p>
  <b>To zip code:</b>
  <%= @shipping_rate.to_zip_code %>
</p>

<p>
  <b>Weight:</b>
  <%= @shipping_rate.weight %>
</p>

<p>
  <b>Ship date:</b>
  <%= @shipping_rate.ship_date %>
</p>

<p>
  <b>Service type:</b>
  <%= @shipping_rate.service_type %>
</p>

<p>
  <b>Package type:</b>
  <%= @shipping_rate.package_type %>
</p>


<%= link_to 'Edit', edit_shipping_rate_path(@shipping_rate) %> |
<%= link_to 'Back', shipping_rates_path %>