config/routes.rb
StampsDemo::Application.routes.draw do
  resources :shipping_labels
  resources :shipping_rates
  resources :addresses
  match '/getrates', :to => 'shipping_labels#add_on_lookup', :via => :post
  # Root is set to the New action to bypass a extra click durring development.
  root :to => 'shipping_labels#new'

end

app/models/shipping_label.rb
class ShippingLabel < ActiveRecord::Base
  include ActiveModel::Validations
  validates_with AddOnValidator

  belongs_to :from_address, :class_name => 'Address', :foreign_key => :from_address_id
  belongs_to :to_address, :class_name => 'Address', :foreign_key => :to_address_id

  # All the available add ons for the given rate from the API
  attr_accessor :available_add_ons

  # The add on codes the merchant has selected
  attr_writer :add_on_codes
  def add_on_codes
    @add_on_codes || []
  end

  attr_accessible :available_add_ons, :to_address_attributes, :ship_date, 
  :service_type, :insurance_amount, :collect_on_delivery, :add_on_codes, 
  :item, :weight, :label_url, :from_address_attributes 

  accepts_nested_attributes_for :from_address, :to_address

  before_create :make_label

  validate :service_type, :presence => true

  def get_rates
    r = Stamps.get_rates(
      :from_zip_code => self.from_address.zip_code,
      :to_zip_code   => self.to_address.zip_code,
      :weight_lb     => self.weight,
      :ship_date     => self.ship_date,
      :service_type  => self.service_type,
      :package_type  => self.item
    )    
    self.available_add_ons = add_ons_from_rate(r.first)
  end

  def make_label
    # Makes a call to the Stamps API with valid data to create a label
    stamp = Stamps.create!(label_options)
    
    if stamp[:errors]
      stamp[:errors].each do |msg|
        self.errors.add(:service_type, msg)
      end
    else
      self.label_url = stamp[:url]
    end

    return self.errors.empty?
  end

  private
  def label_options
    {
      :transaction_id  => Time.now.strftime("%m%d%Y%I%M%S"),
      :tracking_number => true,
      :to => {
        :full_name          => self.to_address.full_name,
        :address1           => self.to_address.address1,
        :city               => self.to_address.city,
        :state              => self.to_address.state,
        :zip_code           => self.to_address.zip_code
      },
      :from => {
        :full_name          => self.from_address.full_name,
        :address1           => self.from_address.address1,
        :city               => self.from_address.city,
        :state              => self.from_address.state,
        :zip_code           => self.from_address.zip_code
      },
      :rate => {
        :from_zip_code => self.from_address.zip_code,
        :to_zip_code   => self.to_address.zip_code,
        :weight_lb     => self.weight,
        :ship_date     => self.ship_date,
        :service_type  => self.service_type,
        :package_type  => self.item
      }.merge(rate_options)
    }
  end

  def rate_options
    rate_options = {
      :add_ons => {
        :add_on_v4 => self.add_on_codes.map {|code| { :add_on_type => code } }
      }
    }
    rate_options = rate_options.merge({:insured_value => self.insurance_amount}) if self.add_on_codes.include? "US-A-INS"
    rate_options = rate_options.merge({:cod_value => self.collect_on_delivery}) if self.add_on_codes.include? "US-A-COD"
    rate_options
  end

  def add_ons_from_rate(rate)
    hash = Hash.new
    rate[:add_ons][:add_on_v4].each do |add_on|
      available = add_on[:add_on_type]
      available = [available] if available.is_a?(String)
      if add_on[:requires_all_of]
        required = add_on[:requires_all_of][:requires_one_of][:add_on_type_v4]
        required = [required] if required.is_a?(String)
      end
      if add_on[:prohibited_with_any_of]
        prohibited = add_on[:prohibited_with_any_of][:add_on_type_v4]
        prohibited = [prohibited] if prohibited.is_a?(String)
      end

      available.each do |code|
        add_on = Hash.new
        add_on["required_add_ons"] = required unless required.blank?
        add_on["prohibited_add_ons"] = prohibited unless prohibited.blank?
        hash[code] = add_on
      end
    end
    hash
  end
end

app/controllers/shipping_labels_controller.rb
class ShippingLabelsController < ApplicationController
  # GET /shipping_labels
  # GET /shipping_labels.json
  def index
    @shipping_labels = ShippingLabel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shipping_labels }
    end
  end

  # GET /shipping_labels/1
  # GET /shipping_labels/1.json
  def show
    @shipping_label = ShippingLabel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shipping_label }
    end
  end

  # GET /shipping_labels/new
  # GET /shipping_labels/new.json
  def new
    @shipping_label = ShippingLabel.new
    @shipping_label.from_address = Address.new
    @shipping_label.to_address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shipping_label }
    end
  end

  # GET /shipping_labels/1/edit
  def edit
    @shipping_label = ShippingLabel.find(params[:id])
  end

  # POST /shipping_labels
  # POST /shipping_labels.json
  def create
    @shipping_label = ShippingLabel.new(params[:shipping_label])
    
    respond_to do |format|
      if @shipping_label.save
        format.html { redirect_to @shipping_label, notice: 'Shipping label was successfully created.' }
        format.json { render json: @shipping_label, status: :created, location: @shipping_label }
      else
        format.html { render action: "new" }
        format.json { render json: @shipping_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shipping_labels/1
  # PUT /shipping_labels/1.json
  def update
    @shipping_label = ShippingLabel.find(params[:id])

    respond_to do |format|
      if @shipping_label.update_attributes(params[:shipping_label])
        format.html { redirect_to @shipping_label, notice: 'Shipping label was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shipping_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipping_labels/1
  # DELETE /shipping_labels/1.json
  def destroy
    @shipping_label = ShippingLabel.find(params[:id])
    @shipping_label.destroy

    respond_to do |format|
      format.html { redirect_to shipping_labels_url }
      format.json { head :no_content }
    end
  end

  def add_on_lookup
    # Create a transient ShippingLabel from the parameters
    @shipping_label = ShippingLabel.new(params[:shipping_label])

    # Find the rates from the API
    @shipping_label.get_rates

    # Render some JS which contains HTML with all the addon checkboxes
    render :partial => 'shipping_labels/add_ons', :locals => { :add_on_codes => @shipping_label.available_add_ons }
  end
end

app/helpers/shipping_labels_helper.rb
module ShippingLabelsHelper
end

app/views/shipping_labels/_add_ons.html.erb
<%= fields_for @shipping_label do |f| %>
	<% @shipping_label.available_add_ons.each do |code, add_on| %>  
	  <div id ="<%= code %>">
		  <%= f.check_box :add_on_codes, { :id => "shipping_label_#{code}", :name => :"shipping_label[add_on_codes][]" }, code, nil %>
	    <%= f.label code, Stamps::Types::ADD_ONS[code] %>
    </div>

    <% if code == "US-A-INS" %>
      <div class="insurance">
        <%= f.label :insurance_amount %><br>
        <%= f.text_field :insurance_amount %>
      </div>
    <% end %>

    <% if code == "US-A-COD" %>
      <div class="cod">
        <%= f.label :collect_on_delivery, "COD amount" %><br>
        <%= f.text_field :collect_on_delivery %>
      </div>
    <% end %>
    
    <% if add_on["required_add_ons"] %>
      <% add_on["required_add_ons"].each do |r| %>
        <%= f.hidden_field :available_add_ons, :name => "shipping_label[available_add_ons][" + code + "][required_add_ons][]", :value => r %>
      <% end %>
    <% end %>

    <% if add_on["prohibited_add_ons"] %>
      <% add_on["prohibited_add_ons"].each do |p| %>
        <%= f.hidden_field :available_add_ons, :name => "shipping_label[available_add_ons][" + code + "][prohibited_add_ons][]", :value => p %>
  	  <% end %>
    <% end %>    
  <% end %>
<% end %>

app/views/shipping_labels/_form.html.erb
<%= form_for(@shipping_label) do |f| %>
  <% if @shipping_label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipping_label.errors.count, "error") %> prohibited this shipping_label from being saved:</h2>

      <ul>
      <% @shipping_label.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Package Deatails</h3>

  <div class="field">
    <%= f.label :item, "Type" %><br />
    <!-- Displays the different types of packages that can be sent -->
    <!-- TODO: Match the package with the correct service types and display only the correct ones with each type of package -->
    <%= f.select :item, Stamps::Types::PACKAGE %>
  </div>

  <div class="field">
    <%= f.label :service_type %><br />
    <!-- Displays the service types that can be used for any given package -->
    <!-- Displays the full name of the service with the value equaling the shorthand -->
    <%= f.select :service_type, Stamps::Types::SERVICE.map { |s| [ s[1], s[0] ] } %>
  </div>

  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>

  <div class="field">
    <%= label_tag 'Ship Date' %><br />
    <%= date_select :shipping_label, :ship_date, :start_year => Date.today.year %>
  </div>

  <h3>From Address</h3>
  <%= f.fields_for :from_address do |a| %>
    <div>
      <%= a.label :full_name %><br />
      <%= a.text_field :full_name %>
    </div>
    <div>
      <%= a.label :address1 %><br />
      <%= a.text_field :address1 %>
    </div>
    <div>
      <%= a.label :city %><br />
      <%= a.text_field :city %>
    </div>
    <div>
      <%= a.label :state %><br />
      <%= a.text_field :state %>
    </div>
    <div>
      <%= a.label :zip_code %><br />
      <%= a.text_field :zip_code %>
    </div>
    <!-- TODO Fill in with other attributes -->
  <% end %>

  <h3>To Address</h3>
  <%= f.fields_for :to_address do |a| %>
    <div>
      <%= a.label :full_name %><br />
      <%= a.text_field :full_name %>
    </div>
    <div>
      <%= a.label :address1 %><br />
      <%= a.text_field :address1 %>
    </div>
    <div>
      <%= a.label :city %><br />
      <%= a.text_field :city %>
    </div>
    <div>
      <%= a.label :state %><br />
      <%= a.text_field :state %>
    </div>
    <div>
      <%= a.label :zip_code %><br />
      <%= a.text_field :zip_code %>
    </div>
  <% end %>

  <div id="add_ons">
    <% unless @shipping_label.available_add_ons.blank? %>
      <%= render :partial => 'shipping_labels/add_ons', :locals => { :add_on_codes => @shipping_label.available_add_ons } %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit 'Print Label' %>
  </div>
<% end %>

app/views/shipping_labels/edit.html.erb
<h1>Editing shipping_label</h1>

<%= render 'form' %>

<%= link_to 'Show', @shipping_label %> |
<%= link_to 'Back', shipping_labels_path %>

app/views/shipping_labels/index.html.erb
<h1>Shipping information</h1>

app/views/shipping_labels/new.html.erb
<h1>New shipping label</h1>

<%= render 'form' %>

<%= link_to 'Back', shipping_labels_path %>

app/views/shipping_labels/show.html.erb
<h4>Your Label</h4>
<p>Please print this page out.</p>
<%=image_tag @shipping_label.label_url %>